---
- name: Secure Coolify with HTTPS (Local Development)
  hosts: coolify
  become: true
  
  vars:
    coolify_domain: coolify.local
    ssl_cert_path: /etc/ssl/certs/coolify-self-signed.crt
    ssl_key_path: /etc/ssl/private/coolify-self-signed.key

  tasks:
    - name: Install prerequisites
      apt:
        name:
          - nginx
          - openssl
        state: present
        update_cache: yes

    - name: Create SSL directory
      file:
        path: /etc/ssl/private
        state: directory
        mode: '0700'

    - name: Generate self-signed SSL certificate
      shell: |
        openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
        -keyout {{ ssl_key_path }} \
        -out {{ ssl_cert_path }} \
        -subj "/CN={{ coolify_domain }}"
      args:
        creates: "{{ ssl_cert_path }}"

    - name: Create nginx configuration for Coolify
      template:
        src: templates/coolify.conf.j2
        dest: /etc/nginx/sites-available/coolify.conf
        mode: '0644'
      notify: reload nginx

    - name: Enable nginx site
      file:
        src: /etc/nginx/sites-available/coolify.conf
        dest: /etc/nginx/sites-enabled/coolify.conf
        state: link
      notify: reload nginx

    - name: Remove default nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: reload nginx

    - name: Ensure nginx is started
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Display success message
      debug:
        msg: 
          - "HTTPS setup completed successfully!"
          - "Coolify is now accessible at https://{{ coolify_domain }}"
          - "NOTE: You will need to accept the self-signed certificate in your browser"

  handlers:
    - name: reload nginx
      service:
        name: nginx
        state: reloaded 